const translations = {
    es: {
        groupName: "Vibe Coding Educativo",
        navWhatIs: "Qué es",
        navCommunity: "Comunidad",
        navApps: "Aplicaciones",
        navResources: "Recursos",
        navNewsletter: "Boletín",
        joinGroup: "Únete al Grupo",
        heroTitle: "Programa con Propósito y Vibe",
        heroSubtitle: "Un espacio para crear, compartir y aprender a desarrollar aplicaciones educativas interactivas con lenguaje natural e Inteligencia Artificial.",
        viewApps: "Ver Aplicaciones",
        viewNewsletter: "Ver Boletín",
        joinTelegram: "Únete en Telegram",
        whatIsTitle: "¿Qué es el Vibe Coding Educativo?",
        whatIsSubtitle: "Una nueva forma de programar, más intuitiva y accesible para todos los educadores.",
        whatIsContent: `<p><strong>Vibe Coding Educativo</strong> es un grupo y una metodología centrada en la creación de aplicaciones para la enseñanza mediante <em>vibe coding</em>: un enfoque de desarrollo basado en <strong>lenguaje natural</strong> y apoyado por modelos de inteligencia artificial 🤖.</p><p>Es un espacio para compartir aplicaciones, resolver dudas técnicas y profundizar en el uso didáctico de esta forma de programación asistida. No necesitas ser un experto en código; si tienes una idea para una herramienta educativa, aquí puedes aprender a hacerla realidad.</p><blockquote class="border-l-4 border-indigo-500 pl-4 italic text-gray-800">"Es hacer programas a través de la IA. Le dices lo que quieres y lo hace." - Juanjo de Haro</blockquote><p>La clave está en la conversación con la IA, refinando la idea paso a paso hasta obtener una aplicación funcional y atractiva que puedes integrar en tus clases y recursos digitales.</p>`,
        learnWord: "Aprender",
        createWord: "Crear",
        communityTitle: "Una Comunidad Abierta y Colaborativa",
        communitySubtitle: "Conectamos con otros apasionados de la tecnología y la educación.",
        card1Title: "Grupo de Telegram",
        card1Desc: "El corazón de nuestra comunidad. Únete para compartir tus proyectos, resolver dudas y aprender de los demás.",
        card1Link: "Unirme al grupo &rarr;",
        card2Title: "ChatGPT-IA-edu",
        card2Desc: "Este grupo está vinculado con la comunidad especializada en el uso educativo de la IA en un sentido más amplio.",
        card2Link: "Visitar grupo &rarr;",
        card3Title: "Conocimiento Abierto",
        card3Desc: "Nos adherimos a los principios del Conocimiento Abierto, fomentando que la tecnología y la educación sean accesibles para todos.",
        card3Link: "Leer principios &rarr;",
        appsTitle: "Galería de Aplicaciones",
        appsSubtitle: "Descubre lo que hemos creado. ¡Inspírate y crea la tuya!",
        exploreRepo: "Explorar el Repositorio Completo",
        addAppNote: "Para añadir tu aplicación, utiliza el formulario oficial disponible en el grupo de Telegram.",
        resourcesTitle: "Recursos y Guías",
        resourcesSubtitle: "Enlaces clave para empezar y profundizar en el Vibe Coding.",
        resource1Title: "Manual de Vibe Coding Educativo",
        resource1Desc: "Una guía completa con extractos de artículos sobre cómo crear aplicaciones, dónde publicarlas y más.",
        resourceLink: "Acceder al manual &rarr;",
        resource2Title: "Cómo activar la IA en recursos educativos",
        resource2Desc: "Aprende a integrar chatbots de IA (Grok, ChatGPT, etc.) en tus materiales digitales como Moodle, eXeLearning o Google Sites.",
        readArticle: "Leer el artículo &rarr;",
        newsletterTitle: "Boletín Semanal",
        newsletterSubtitle: "Un resumen de las conversaciones, recursos y proyectos más destacados de la comunidad.",
        newsletterDesc: "Cada semana, recopilamos lo más relevante de nuestro grupo de Telegram para que no te pierdas nada. Descubre nuevas herramientas, debates interesantes y las últimas creaciones de los miembros.",
        readNewsletter: "Leer el último boletín",
        footerTitle: "Participa, comparte, aprende y programa con propósito y vibe.",
        joinConversation: "Únete a la conversación",
        footerCommunity: "Comunidad Vibe Coding Educativo.",
        footerLicense: "Licencia Creative Commons BY-SA"
    },
    ca: {
        groupName: "Vibe Coding Educatiu",
        navWhatIs: "Què és",
        navCommunity: "Comunitat",
        navApps: "Aplicacions",
        navResources: "Recursos",
        navNewsletter: "Butlletí",
        joinGroup: "Uneix-t'hi al Grup",
        heroTitle: "Programa amb Propòsit i Vibe",
        heroSubtitle: "Un espai per a crear, compartir i aprendre a desenvolupar aplicacions educatives interactives amb llenguatge natural i Intel·ligència Artificial.",
        viewApps: "Veure Aplicacions",
        viewNewsletter: "Veure Butlletí",
        joinTelegram: "Uneix-t'hi a Telegram",
        whatIsTitle: "Què és el Vibe Coding Educatiu?",
        whatIsSubtitle: "Una nova manera de programar, més intuïtiva i accessible per a tots els educadors.",
        whatIsContent: `<p><strong>Vibe Coding Educatiu</strong> és un grup i una metodologia centrada en la creació d'aplicacions per a l'ensenyament mitjançant <em>vibe coding</em>: un enfocament de desenvolupament basat en <strong>llenguatge natural</strong> i recolzat per models d'intel·ligència artificial 🤖.</p><p>És un espai per compartir aplicacions, resoldre dubtes tècnics i aprofundir en l'ús didàctic d'aquesta forma de programació assistida. No necessites ser un expert en codi; si tens una idea per a una eina educativa, aquí pots aprendre a fer-la realitat.</p><blockquote class="border-l-4 border-indigo-500 pl-4 italic text-gray-800">"És fer programes a través de la IA. Li dius el que vols i ho fa." - Juanjo de Haro</blockquote><p>La clau està en la conversa amb la IA, refinant la idea pas a pas fins a obtenir una aplicació funcional i atractiva que pots integrar a les teves classes i recursos digitals.</p>`,
        learnWord: "Aprendre",
        createWord: "Crear",
        communityTitle: "Una Comunitat Oberta i Col·laborativa",
        communitySubtitle: "Connectem amb altres apassionats de la tecnologia i l'educació.",
        card1Title: "Grup de Telegram",
        card1Desc: "El cor de la nostra comunitat. Uneix-t'hi per compartir els teus projectes, resoldre dubtes i aprendre dels altres.",
        card1Link: "Unir-me al grup &rarr;",
        card2Title: "ChatGPT-IA-edu",
        card2Desc: "Aquest grup està vinculat amb la comunitat especialitzada en l'ús educatiu de la IA en un sentit més ampli.",
        card2Link: "Visitar grup &rarr;",
        card3Title: "Coneixement Obert",
        card3Desc: "Ens adherim als principis del Coneixement Obert, fomentant que la tecnologia i l'educació siguin accessibles per a tothom.",
        card3Link: "Llegir principis &rarr;",
        appsTitle: "Galeria d'Aplicacions",
        appsSubtitle: "Descobreix el que hem creat. Inspira't i crea la teva!",
        exploreRepo: "Explorar el Repositori Complet",
        addAppNote: "Per afegir la teva aplicació, utilitza el formulari oficial disponible al grup de Telegram.",
        resourcesTitle: "Recursos i Guies",
        resourcesSubtitle: "Enllaços clau per començar i aprofundir en el Vibe Coding.",
        resource1Title: "Manual de Vibe Coding Educatiu",
        resource1Desc: "Una guia completa amb extractes d'articles sobre com crear aplicacions, on publicar-les i més.",
        resourceLink: "Accedir al manual &rarr;",
        resource2Title: "Com activar la IA en recursos educatius",
        resource2Desc: "Aprèn a integrar chatbots d'IA (Grok, ChatGPT, etc.) als teus materials digitals com Moodle, eXeLearning o Google Sites.",
        readArticle: "Llegir l'article &rarr;",
        newsletterTitle: "Butlletí Setmanal",
        newsletterSubtitle: "Un resum de les converses, recursos i projectes més destacats de la comunitat.",
        newsletterDesc: "Cada setmana, recopilem el més rellevant del nostre grup de Telegram perquè no et perdis res. Descobreix noves eines, debats interessants i les últimes creacions dels membres.",
        readNewsletter: "Llegir l'últim butlletí",
        footerTitle: "Participa, comparteix, aprèn i programa amb propòsit i vibe.",
        joinConversation: "Uneix-te a la conversa",
        footerCommunity: "Comunitat Vibe Coding Educatiu.",
        footerLicense: "Llicència Creative Commons BY-SA"
    },
    gl: {
        groupName: "Vibe Coding Educativo",
        navWhatIs: "Que é",
        navCommunity: "Comunidade",
        navApps: "Aplicacións",
        navResources: "Recursos",
        navNewsletter: "Boletín",
        joinGroup: "Únete ao Grupo",
        heroTitle: "Programa con Propósito e Vibe",
        heroSubtitle: "Un espazo para crear, compartir e aprender a desenvolver aplicacións educativas interactivas con linguaxe natural e Intelixencia Artificial.",
        viewApps: "Ver Aplicacións",
        viewNewsletter: "Ver Boletín",
        joinTelegram: "Únete en Telegram",
        whatIsTitle: "Que é o Vibe Coding Educativo?",
        whatIsSubtitle: "Unha nova forma de programar, máis intuitiva e accesible para todos os educadores.",
        whatIsContent: `<p><strong>Vibe Coding Educativo</strong> é un grupo e unha metodoloxía centrada na creación de aplicacións para o ensino mediante <em>vibe coding</em>: un enfoque de desenvolvemento baseado na <strong>linguaxe natural</strong> e apoiado por modelos de intelixencia artificial 🤖.</p><p>É un espazo para compartir aplicacións, resolver dúbidas técnicas e profundar no uso didáctico desta forma de programación asistida. Non necesitas ser un experto en código; se tes unha idea para unha ferramenta educativa, aquí podes aprender a facela realidade.</p><blockquote class="border-l-4 border-indigo-500 pl-4 italic text-gray-800">"É facer programas a través da IA. Diceslle o que queres e faino." - Juanjo de Haro</blockquote><p>A clave está na conversa coa IA, refinando a idea paso a paso ata obter unha aplicación funcional e atractiva que podes integrar nas túas clases e recursos dixitais.</p>`,
        learnWord: "Aprender",
        createWord: "Crear",
        communityTitle: "Unha Comunidade Aberta e Colaborativa",
        communitySubtitle: "Conectamos con outros apaixonados da tecnoloxía e a educación.",
        card1Title: "Grupo de Telegram",
        card1Desc: "O corazón da nosa comunidade. Únete para compartir os teus proxectos, resolver dúbidas e aprender dos demais.",
        card1Link: "Unirme ao grupo &rarr;",
        card2Title: "ChatGPT-IA-edu",
        card2Desc: "Este grupo está vencellado coa comunidade especializada no uso educativo da IA nun sentido máis amplo.",
        card2Link: "Visitar grupo &rarr;",
        card3Title: "Coñecemento Aberto",
        card3Desc: "Adherímonos aos principios do Coñecemento Aberto, fomentando que a tecnoloxía e a educación sexan accesibles para todos.",
        card3Link: "Ler principios &rarr;",
        appsTitle: "Galería de Aplicacións",
        appsSubtitle: "Descubre o que creamos. Inspírate e crea a túa!",
        exploreRepo: "Explorar o Repositorio Completo",
        addAppNote: "Para engadir a túa aplicación, utiliza o formulario oficial dispoñible no grupo de Telegram.",
        resourcesTitle: "Recursos e Guías",
        resourcesSubtitle: "Ligazóns clave para comezar e profundar no Vibe Coding.",
        resource1Title: "Manual de Vibe Coding Educativo",
        resource1Desc: "Unha guía completa con extractos de artigos sobre como crear aplicacións, onde publicalas e máis.",
        resourceLink: "Acceder ao manual &rarr;",
        resource2Title: "Como activar a IA en recursos educativos",
        resource2Desc: "Aprende a integrar chatbots de IA (Grok, ChatGPT, etc.) nos teus materiais dixitais como Moodle, eXeLearning ou Google Sites.",
        readArticle: "Ler o artigo &rarr;",
        newsletterTitle: "Boletín Semanal",
        newsletterSubtitle: "Un resumo das conversas, recursos e proxectos máis destacados da comunidade.",
        newsletterDesc: "Cada semana, recompilamos o más relevante do noso grupo de Telegram para que non te perdas nada. Descobre novas ferramentas, debates interesantes e as últimas creacións dos membros.",
        readNewsletter: "Ler o último boletín",
        footerTitle: "Participa, comparte, aprende e programa con propósito e vibe.",
        joinConversation: "Únete á conversa",
        footerCommunity: "Comunidade Vibe Coding Educativo.",
        footerLicense: "Licenza Creative Commons BY-SA"
    },
    eu: {
        groupName: "Vibe Coding Hezitzailea",
        navWhatIs: "Zer da",
        navCommunity: "Komunitatea",
        navApps: "Aplikazioak",
        navResources: "Baliabideak",
        navNewsletter: "Buletina",
        joinGroup: "Sartu Taldean",
        heroTitle: "Programatu Helburu eta Viberekin",
        heroSubtitle: "Aplikazio hezitzaile interaktiboak hizkuntza naturalarekin eta Adimen Artifizialarekin sortzeko, partekatzeko eta ikasteko gunea.",
        viewApps: "Ikusi Aplikazioak",
        viewNewsletter: "Ikusi Buletina",
        joinTelegram: "Sartu Telegramen",
        whatIsTitle: "Zer da Vibe Coding Hezitzailea?",
        whatIsSubtitle: "Programatzeko modu berri bat, hezitzaile guztientzat intuitiboagoa eta eskuragarriagoa.",
        whatIsContent: `<p><strong>Vibe Coding Hezitzailea</strong> irakaskuntzarako aplikazioak sortzera bideratutako talde eta metodologia bat da, <em>vibe coding</em> bidez: <strong>hizkuntza naturalean</strong> oinarritutako eta adimen artifizialeko ereduek lagundutako garapen-ikuspegia 🤖.</p><p>Aplikazioak partekatzeko, zalantza teknikoak argitzeko eta programazio-modu lagundu honen erabilera didaktikoan sakontzeko gunea da. Ez duzu zertan kodean aditua izan; tresna hezitzaile baterako ideia bat baduzu, hemen errealitate bihurtzen ikas dezakezu.</p><blockquote class="border-l-4 border-indigo-500 pl-4 italic text-gray-800">"Programak IAren bidez egitea da. Zer nahi duzun esaten diozu eta berak egiten du." - Juanjo de Haro</blockquote><p>Gakoa IA-rekin elkarrizketan datza, ideia pausoz pauso fintzen, zure klaseetan eta baliabide digitaletan integra dezakezun aplikazio funtzional eta erakargarri bat lortu arte.</p>`,
        learnWord: "Ikasi",
        createWord: "Sortu",
        communityTitle: "Komunitate Ireki eta Kolaboratiboa",
        communitySubtitle: "Teknologiaren eta hezkuntzaren beste zale batzuekin konektatzen dugu.",
        card1Title: "Telegram Taldea",
        card1Desc: "Gure komunitatearen bihotza. Bat egin zure proiektuak partekatzeko, zalantzak argitzeko eta besteengandik ikasteko.",
        card1Link: "Taldean sartu &rarr;",
        card2Title: "ChatGPT-IA-edu",
        card2Desc: "Talde hau IAren erabilera hezitzailean espezializatutako komunitatearekin lotuta dago zentzu zabalagoan.",
        card2Link: "Taldea bisitatu &rarr;",
        card3Title: "Ezagutza Irekia",
        card3Desc: "Ezagutza Irekiaren printzipioekin bat egiten dugu, teknologia eta hezkuntza guztiontzat eskuragarri egon daitezen sustatuz.",
        card3Link: "Printzipioak irakurri &rarr;",
        appsTitle: "Aplikazioen Galeria",
        appsSubtitle: "Ezagutu zer sortu dugun. Inspiratu zaitez eta sortu zurea!",
        exploreRepo: "Arakatu Repositorio Osoa",
        addAppNote: "Zure aplikazioa gehitzeko, erabili Telegram taldean eskuragarri dagoen formulario ofiziala.",
        resourcesTitle: "Baliabideak eta Gidak",
        resourcesSubtitle: "Vibe Coding-en hasteko eta sakontzeko funtsezko estekak.",
        resource1Title: "Vibe Coding Hezitzailearen Eskuliburua",
        resource1Desc: "Gida osoa, aplikazioak nola sortu, non argitaratu eta gehiagori buruzko artikuluen pasarteekin.",
        resourceLink: "Eskuliburura joan &rarr;",
        resource2Title: "Nola aktibatu IA hezkuntza-baliabideetan",
        resource2Desc: "Ikasi nola integratu IAko chatbotak (Grok, ChatGPT, etab.) zure material digitaletan, hala nola Moodle, eXeLearning edo Google Sites.",
        readArticle: "Artikulua irakurri &rarr;",
        newsletterTitle: "Asteko Buletina",
        newsletterSubtitle: "Komunitateko elkarrizketa, baliabide eta proiektu nabarmenenen laburpena.",
        newsletterDesc: "Astero, gure Telegram taldeko garrantzitsuena biltzen dugu, ezer galdu ez dezazun. Ezagutu tresna berriak, eztabaida interesgarriak eta kideen azken sorkuntzak.",
        readNewsletter: "Irakurri azken buletina",
        footerTitle: "Parte hartu, partekatu, ikasi eta programatu helburu eta viberekin.",
        joinConversation: "Sartu elkarrizketan",
        footerCommunity: "Vibe Coding Educativo Komunitatea.",
        footerLicense: "Creative Commons BY-SA Lizentzia"
    },
    en: {
        groupName: "Educational Vibe Coding",
        navWhatIs: "What is it",
        navCommunity: "Community",
        navApps: "Apps",
        navResources: "Resources",
        navNewsletter: "Newsletter",
        joinGroup: "Join the Group",
        heroTitle: "Code with Purpose and Vibe",
        heroSubtitle: "A space to create, share, and learn to develop interactive educational applications with natural language and Artificial Intelligence.",
        viewApps: "View Apps",
        viewNewsletter: "View Newsletter",
        joinTelegram: "Join on Telegram",
        whatIsTitle: "What is Educational Vibe Coding?",
        whatIsSubtitle: "A new way of programming, more intuitive and accessible for all educators.",
        whatIsContent: `<p><strong>Educational Vibe Coding</strong> is a group and methodology focused on creating applications for teaching through <em>vibe coding</em>: a development approach based on <strong>natural language</strong> and supported by artificial intelligence models 🤖.</p><p>It is a space to share applications, solve technical doubts, and delve into the didactic use of this form of assisted programming. You don't need to be a coding expert; if you have an idea for an educational tool, you can learn to make it a reality here.</p><blockquote class="border-l-4 border-indigo-500 pl-4 italic text-gray-800">"It's about making programs through AI. You tell it what you want, and it does it." - Juanjo de Haro</blockquote><p>The key is the conversation with the AI, refining the idea step by step to obtain a functional and attractive application that you can integrate into your classes and digital resources.</p>`,
        learnWord: "Learn",
        createWord: "Create",
        communityTitle: "An Open and Collaborative Community",
        communitySubtitle: "We connect with other technology and education enthusiasts.",
        card1Title: "Telegram Group",
        card1Desc: "The heart of our community. Join to share your projects, solve doubts, and learn from others.",
        card1Link: "Join the group &rarr;",
        card2Title: "ChatGPT-AI-edu",
        card2Desc: "This group is linked to the community specializing in the educational use of AI in a broader sense.",
        card2Link: "Visit group &rarr;",
        card3Title: "Open Knowledge",
        card3Desc: "We adhere to the principles of Open Knowledge, promoting that technology and education are accessible to all.",
        card3Link: "Read principles &rarr;",
        appsTitle: "Application Gallery",
        appsSubtitle: "Discover what we've created. Get inspired and create your own!",
        exploreRepo: "Explore the Full Repository",
        addAppNote: "To add your application, use the official form available in the Telegram group.",
        resourcesTitle: "Resources and Guides",
        resourcesSubtitle: "Key links to get started and delve deeper into Vibe Coding.",
        resource1Title: "Educational Vibe Coding Manual",
        resource1Desc: "A complete guide with excerpts from articles on how to create applications, where to publish them, and more.",
        resourceLink: "Access the manual &rarr;",
        resource2Title: "How to activate AI in educational resources",
        resource2Desc: "Learn how to integrate AI chatbots (Grok, ChatGPT, etc.) into your digital materials like Moodle, eXeLearning, or Google Sites.",
        readArticle: "Read the article &rarr;",
        newsletterTitle: "Weekly Newsletter",
        newsletterSubtitle: "A summary of the community's most outstanding conversations, resources, and projects.",
        newsletterDesc: "Every week, we compile the most relevant content from our Telegram group so you don't miss a thing. Discover new tools, interesting debates, and the latest creations from our members.",
        readNewsletter: "Read the latest newsletter",
        footerTitle: "Participate, share, learn, and code with purpose and vibe.",
        joinConversation: "Join the conversation",
        footerCommunity: "Vibe Coding Educativo Community.",
        footerLicense: "Creative Commons BY-SA License"
    }
};

function setLanguage(lang) {
    if (!translations[lang]) return;
    document.documentElement.lang = lang;
    const langStrings = translations[lang];
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.dataset.lang;
        if (langStrings[key]) {
            el.innerHTML = langStrings[key];
        }
    });
    localStorage.setItem('vibeLang', lang);
}

function getInitialLanguage() {
    const savedLang = localStorage.getItem('vibeLang');
    if (savedLang && translations[savedLang]) {
        return savedLang;
    }
    const browserLang = navigator.language.split('-')[0];
    return translations[browserLang] ? browserLang : 'es';
}

export { setLanguage, getInitialLanguage };